### ISSUE TITLE
Wrong configuration

### ISSUE THREAD

**Issue by michaelmyc** [basdp/vscode-language-gas-x86#1]
In package.json, you have the configuration set to ./language-configuration.json, but you have the file named to gas.configuration.json. 

I'll fork it to see if it works, and I'll keep you updated. Please accept my merge request when I submit one. If you don't feel like maintaining this project any more, please add me to collaborator and I'll try my best to maintain it.

**Comment by basdp** [comment]
@tydlwav Please check it, i'll accept your PR.

**Comment by basdp** [comment]
Has been fixed with #2.
