### ISSUE TITLE
Update version on visual studio code marketplace

### ISSUE THREAD

**Issue by cvl01** [basdp/vscode-language-gas-x86#3]
I noticed the version of github has some changes/improvements that are not published on https://marketplace.visualstudio.com/items?itemName=basdp.language-gas-x86&ssr=false#overview

Can you update this version please?

**Comment by basdp** [comment]
@cvl01 Thanks for noticing this. I will publish the new version to the marketplace.

**Comment by basdp** [comment]
Version 0.0.2 is now live.
