### ISSUE TITLE
Publish the extension on the Open VSX Registry

### ISSUE THREAD

**Issue by RMPR** [basdp/vscode-language-gas-x86#5]
Hello, thanks for this very useful extension. This is a request to make it available on the [Open VSX Registry](https://open-vsx.org/) to make it easier to install. Since the VSCode marketplace is proprietary, the creators of [Onivim](https://onivim.github.io) decided to use Open VSX instead [more info here](https://onivim.github.io/docs/configuration/extensions). Right now your extension needs to be installed from the CLI.

**Comment by basdp** [comment]
Great idea. I have created a Github Actions pipeline that automatically pushes new versions to open-VSX. The package is published at the following place: https://open-vsx.org/extension/basdp/language-gas-x86

Note that my account is still unverified, but I have requested a verification at: https://github.com/EclipseFdn/open-vsx.org/issues/345
