### ISSUE TITLE
Language server doesn't work in VS Code

### ISSUE THREAD

**Issue by bnjmnjrk** [basdp/vscode-language-gas-x86#7]
As you can see in the picture at the bottom, it looks like the language server isn't working.
Because of no information about features in the readme.md, it is not clear, what features are expected to work.

![Screenshot from 2023-09-02 15-39-46](https://github.com/basdp/vscode-language-gas-x86/assets/106487517/abddeaec-e03a-4e47-b3ca-fb3c0f1908ba)

**Comment by basdp** [comment]
What file extension are you using?

**Comment by bnjmnjrk** [comment]
I use the `.asm` file extension

**Comment by basdp** [comment]
Ah okay. That's it. I added the `.asm` extension in the manifest. Typically GAS code has the extension `.s` though.
